routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within  a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return to_route('login');


});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// dashboard routes
Route::prefix('admin')->name('admin.')->middleware(['web', 'auth'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::get('remove-favorite/{id}', [HomeController::class, 'removeFavorite'])->name('remove.favorite');
    Route::get('contacts/get-data', [ContactController::class, 'getData']);
    Route::resource('/contacts', ContactController::class);
    Route::resource('users', UserController::class);
    Route::post('/users_password', [UserController::class, 'changePassword'])->name('password.update');
    Route::get('bookmark-contact/{id}', [ContactController::class, 'bookmarkContact'])->name('contact.bookmark');

});

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ContactRequest;
use App\Models\Contact;
use App\Services\ContactService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\JsonResponse;

class ContactController extends Controller
{

    protected ContactService $service;
    protected string $redirectUrl;
    const moduleDirectory = 'admin.contacts.';


    public function __construct(ContactService $contactService)
    {
        $this->middleware('auth');
        $this->redirectUrl = 'admin/contacts';
        $this->service = $contactService;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): View
    {
        $data = [
            'pageTitle' => 'Contact List',
            'tableHeads' => ['Sr. No', 'Image', 'Name', 'Email', 'Phone No', 'Mark Favorite', 'Action'],
            'dataUrl' => $this->redirectUrl . '/get-data',
            'columns' => [
                ['data' => 'id', 'name' => 'id'],
                ['data' => 'image', 'name' => 'image'],
                ['data' => 'name', 'name' => 'name'],
                ['data' => 'email', 'name' => 'email'],
                ['data' => 'phone_no', 'name' => 'phone_no'],
                ['data' => 'isFavorite', 'name' => 'isFavorite'],
                ['data' => 'action', 'name' => 'action', 'orderable' => false],
            ],
        ];
        return view(self::moduleDirectory . 'index', $data);
    }

    public function getData(Request $request): JsonResponse
    {
        return $this->service->getAllData($request);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(): View
    {
        $data = ['pageTitle' => 'Contact Create',];
        return view(self::moduleDirectory . 'create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContactRequest $request): RedirectResponse
    {
        $contacts = $this->service->saveContact($request);
        if ($contacts) {
            $request->session()->flash('success', setMessage('create', 'Contact'));
        } else {
            $request->session()->flash('error', setMessage('create.error', 'Contact'));
        }
        return redirect()->route('admin.contacts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact):View
    {
        $data = [
            'pageTitle' => 'Contact Detail',
            'contact' => $contact,
        ];
        return view(self::moduleDirectory.'view', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact):View
    {
        $data = [
            'pageTitle' => 'Contact Edit',
            'contact' => $contact,
        ];
        return view(self::moduleDirectory.'edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function update(ContactRequest $request, Contact $contact):RedirectResponse
    {
        $contact = $this->service->updateContact($request, $contact);

        if ($contact) {
            $request->session()->flash('success', setMessage('update', 'Contact'));
        } else {
            $request->session()->flash('error', setMessage('update.error', 'Contact'));
        }
        return redirect()->route('admin.contacts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Contact $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy($id): JsonResponse
    {
        $contact = $this->service->find($id);
        if (file_exists('assets/uploads/contact/image/' . $contact->image)) {
            unlink('assets/uploads/contact/image/' . $contact->image);
        }
        $contact->delete();
        return response()->json(['status' => true, 'data' => $contact]);
    }

    //bookMark as a favorite
    public function bookmarkContact(Request $request, $id): RedirectResponse
    {
        $contact = $this->service->find($id);
        $isFavorite = $contact->isFavorite == 0 ? 1 : 0;
        $contact->update(['isFavorite' => $isFavorite]);
        if ($contact) {
            if ($contact->isFavorite == 1) {
                $request->session()->flash('success', ucfirst($contact->name) . 'is Now Marked As Favorite ');
            }
            if ($contact->isFavorite == 0) {
                $request->session()->flash('success', ucfirst($contact->name) . 'is Now Removed From Favorite ');
            }
        } else {
            $request->session()->flash('error', 'Failed To Mark ');
        }
        return redirect()->route('admin.contacts.index');

    }
}

resources/views/admin/contacts/create.blade.php
@extends('admin.layouts.app')
@section('pageTitle', $pageTitle)

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-custom">
                    <div class="card-header">
                        <h3 class="card-title">{{$pageTitle}}</h3>
                        <div class="card-toolbar">
                            <div class="example-tools justify-content-center">
                                <a href="{{route('admin.contacts.index')}}" class="btn btn-primary mr-3"><i class="flaticon-list-2"></i>Contacts</a>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form action="{{ route('admin.contacts.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="form-control-label">Name<span class="text-danger">*</span></label>
                                            <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" value="{{ old('name') }}" placeholder="Enter Contact Name" />
                                            @if ($errors->has('name'))
                                                <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="form-control-label">Email<span class="text-danger"></span></label>
                                            <input type="email" name="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" value="{{ old('email') }}" placeholder="Enter Contact Email" />
                                            @if ($errors->has('email'))
                                                <div class="invalid-feedback">{{ $errors->first('email') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="form-control-label">Phone<span class="text-danger">*</span></label>
                                            <input type="text" name="phone_no" class="form-control {{ $errors->has('phone_no') ? 'is-invalid' : '' }}" value="{{ old('phone_no') }}" placeholder="Enter Phone No"/>
                                            @if ($errors->has('phone_no'))
                                                <div class="invalid-feedback">{{ $errors->first('phone_no') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>


                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="form-control-label">Additional Phone No<span class="text-danger"></span></label>
                                            <input type="text" name="additional_phones" class="form-control {{ $errors->has('additional_phones') ? 'is-invalid' : '' }}" value="{{ old('additional_phones') }}" placeholder="Enter Other Phone No" />
                                            @if ($errors->has('additional_phones'))
                                                <div class="invalid-feedback">{{ $errors->first('additional_phones') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>


                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <label>Image<span class="text-danger"></span></label>
                                        <div></div>
                                        <div class="custom-file">
                                            <input type="file" name="image" class="custom-file-input form-control {{ $errors->has('image') ? 'is-invalid' : '' }}" id="OrganizationImageFile" />
                                            <label class="custom-file-label" for="OrganizationImageFile">Choose file</label>
                                            @if ($errors->has('image'))
                                                <div class="invalid-feedback">{{ $errors->first('image') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success mr-3"><i class="flaticon2-paperplane"></i>Save</button>
                            <a href="{{ route('admin.contacts.index') }}" class="btn btn-danger"><i class="flaticon-close"></i> Cancel</a>

                        </div>
                    </form>
                    <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/contacts/edit.blade.php
@extends('admin.layouts.app')
@section('pageTitle', $pageTitle)

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-custom">
                    <div class="card-header">
                        <h3 class="card-title">{{$pageTitle}}</h3>
                        <div class="card-toolbar">
                            <div class="example-tools justify-content-center">
                                <a href="{{route('admin.contacts.index')}}" class="btn btn-primary mr-3"><i class="flaticon-list-2"></i>Contact</a>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form action="{{ route('admin.contacts.update', $contact->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="form-control-label">Name<span class="text-danger">*</span></label>
                                            <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" value="{{ old('name', $contact->name) }}" placeholder="Contact Name" />
                                            @if ($errors->has('name'))
                                                <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="form-control-label">Email<span class="text-danger"></span></label>
                                            <input type="email" name="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" value="{{ old('email',  $contact->email) }}" placeholder="Contact Email" />
                                            @if ($errors->has('email'))
                                                <div class="invalid-feedback">{{ $errors->first('email') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="form-control-label">Phone<span class="text-danger">*</span></label>
                                            <input type="text" name="phone_no" class="form-control {{ $errors->has('phone_no') ? 'is-invalid' : '' }}" value="{{ old('phone_no', $contact->phone_no) }}" placeholder="Contact Phone" />
                                            @if ($errors->has('phone_no'))
                                                <div class="invalid-feedback">{{ $errors->first('phone_no') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="form-control-label">Additional Phone No<span class="text-danger"></span></label>
                                            <input type="text" name="additional_phones" class="form-control {{ $errors->has('additional_phones') ? 'is-invalid' : '' }}" value="{{ old('additional_phones', $contact->additional_phones) }}" placeholder="Contact Phone" />
                                            @if ($errors->has('additional_phones'))
                                                <div class="invalid-feedback">{{ $errors->first('additional_phones') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>


                                <div class="col-sm-2 col-md-6">
                                    <div class="form-group">
                                        <label for="exampleSelect1">Is Favorite<span class="text-danger"></span></label>
                                        <select class="form-control" name="isFavorite">
                                            <option value="1" {{$contact->isFavorite == 1 ? 'selected' : ''}}>Yes</option>
                                            <option value="0" {{$contact->isFavorite == 0 ? 'selected' : ''}}>No</option>
                                        </select>
                                    </div>
                                </div>


                                <div class="col-sm-12 col-md-6">
                                    <div class="form-group">
                                        <label>Image<span class="text-danger"></span></label>
                                        <div></div>
                                        <div class="custom-file">
                                            <input type="file" name="image" class="custom-file-input form-control {{ $errors->has('image') ? 'is-invalid' : '' }}" id="OrganizationImageFile" />
                                            <label class="custom-file-label" for="OrganizationImageFile">Choose file</label>
                                            <div id="emailHelp" class="form-text">Don't browse if want to keep old one</div>

                                            @if ($errors->has('image'))
                                                <div class="invalid-feedback">{{ $errors->first('image') }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success mr-3"> <i class="flaticon2-paperplane"></i>Update</button>
                            <a href="{{ route('admin.contacts.index') }}" class="btn btn-danger"><i class="flaticon-close"></i> Cancel</a>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/contacts/index.blade.php
@extends('admin.layouts.app')
@section('pageTitle', $pageTitle)

@section('content')
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <!--begin::Card-->
                <div class="card card-custom gutter-b">
                    <div class="card-header flex-wrap py-3">
                        <div class="card-title">
                            <h3 class="card-label">Contacts List</h3>
                        </div>
                        <div class="card-toolbar">

                            <!--begin::Button-->
                                <a href="{{route('admin.contacts.create')}}" class="btn btn-success">
                                    <i class="flaticon2-plus-1"></i> Add New
                                </a>
                                <!--end::Button-->

                        </div>
                    </div>


                    <div class="card-body">
                        <div class="m-section__content">
                            <form id="searchForm" role="form" method="post">
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="name" placeholder="Search Name">
                                            </div>
                                        </div>

                                        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="email" placeholder="Search Email">
                                            </div>
                                        </div>

                                        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="phone_no" placeholder="Search Phone No">
                                            </div>
                                        </div>

                                        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
                                            <div class="form-group">
                                                <select class="form-control" name="isFavorite">
                                                    <option value="">Search By Favorite Or Not</option>
                                                    <option value="1">Favorite</option>
                                                    <option value="0">General</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="clearfix">
                                            <hr/>
                                        </div>

                                        <div class="col-md-12 text">
                                            <div class="text-center search-action-btn">
                                                <button class="btn btn-info m-btn m-btn--icon">
                                                    <i class="fa fa-search"></i> Search
                                                </button>
                                                <button type="reset" class="btn btn-primary reset"><i
                                                        class="fas fa-sync-alt search-reset"></i> Reset
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                    <br/>
                                </div>
                            </form>

                        </div>


                        <!--begin: Datatable-->
                    @include('admin.common.datatable')
                    <!--end: Datatable-->
                    </div>
                </div>
                <!--end::Card-->
            </div>
        </div>
    </div>

    <!-- delete contact modal start-->
    <div class="modal fade" id="contact-delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" >Delete Contact</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body py-3">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                            <div class="form-group  m-form__group mb-0">
                                <input type="hidden" name="id" id="contactId">
                                <h5 class="text-danger mb-0">Are you Sure want to delete ?</h5>
                            </div>
                        </div>
                    </div>
                </div>
                <div class= "modal-footer">
                    {{-- <button type="submit" class="btn btn-success mr-3"><i class="flaticon2-paperplane"></i>Save</button>
                     <button type="reset" class="btn btn-danger"><i class="flaticon-close"></i>Cancel</button>--}}

                    <button type="button" class="btn btn-danger mr-3" data-dismiss="modal"><i class="flaticon-close"></i> Close</button>
                    <button type="button" class="btn btn-success" id="delete-contact-btn"><i class="flaticon2-paperplane"></i> Submit</button>
                </div>
            </div>
        </div>
    </div>

@endsection

@once
    @push('scripts')
        <script src="{{asset('assets/global/datatables/datatables.bundle.js')}}"></script>

        <script>
            $(document).on('click', '.btn-delete', function (e) {
                var contactId = $(this).data('contact-id')
                $('#contactId').val(contactId);
                $('#contact-delete-modal').modal('show');
            });

            $('#delete-contact-btn').click(function (e) {
                e.preventDefault();
                var contactId = $('#contactId').val();
                $.ajax({
                    type: 'DELETE',
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    url: baseUrl+ 'admin/contacts/'+contactId,
                    dataType: 'JSON',
                    data: {
                        'contactId': contactId,
                    },
                    processData: false,
                    contentType: false,
                    success: function(response) {
                        $('#contact-delete-modal').modal('hide');
                        Swal.fire({
                            icon: 'success',
                            title: 'Success',
                            text: "Item Deleted successfully",
                            type: 'success',
                            showConfirmButton: true,
                            timer: 9000
                        });
                        location.reload();

                    },
                    error: function (xhr) {
                        $('#contact-delete-modal').modal('hide');
                        Swal.fire({
                            icon: 'error',
                            title: 'Oops...',
                            text: "You have no access to delete",
                            type: 'error',
                            showConfirmButton: false,
                            //confirmButtonText: 'Yes'
                            timer: 5000
                        });
                        location.reload();
                        console.log(xhr.responseText);
                    }
                });
            })
        </script>
    @endpush
@endonce